apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ridelevel-com-tls
spec:
  secretName: ridelevel-com
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  commonName: ridelevel.com
  dnsNames:
    - ridelevel.com
    - www.ridelevel.com
  acme:
    config:
      - http01: 
          ingressClass: nginx
        domains:
          - ridelevel.com
          - www.ridelevel.com